version: 3.0.7
docker_context: .
build_docker_file: docker/Dockerfile.building
build_method: pytest_run
update_method: python_update
python_version_file: http_client/version.py
deploy_method: python_upload_to_index
type: library
changelog: true
