# syntax=docker/dockerfile:1.4
FROM registry.pyn.ru/python3.9-bullseye-building:2025.01.28

RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

COPY poetry.lock /home/building/poetry.lock
COPY pyproject.toml /home/building/pyproject.toml
WORKDIR /home/building

RUN --mount=type=ssh poetry install --no-root

COPY http_client /home/building/http_client/
COPY tests /home/building/tests/

CMD ["pytest"]
