# syntax=docker/dockerfile:1.4
FROM registry.pyn.ru/python3.11-bullseye-building:2023.08.09

RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

COPY poetry.lock pyproject.toml /home/building/
COPY http_client /home/building/http_client/
COPY tests /home/building/tests/
WORKDIR /home/building

RUN --mount=type=ssh poetry install --no-root
